<?php
	$config_db_server='localhost';
	$config_db_server_username='ovreuropa_user';
	$config_db_server_password='#D.MBle~a)3x';
	$config_db_database='ovreuropa_db';
	$config_db_charset='utf8';
	$config_db_collation='utf8_general_ci';
	$config_table_prefix='class_';
	$config_live_site='http://127.0.0.70';
	$config_abs_path='E:\workspace\oxy\OxyClassifieds-v9.7';
	$config_demo=0;
	$config_debug=0;
	$config_data_set='general';
?>
